src/Entity/RequestService.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RequestServiceRepository")
 */
class RequestService
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_create;

    /**
     * @ORM\Column(type="integer")
     */
    private $type_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $client_id;

    /**
     * @ORM\Column(type="text")
     */
    private $body;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $response;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $channel;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $priority;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $parent_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateCreate(): ?\DateTimeInterface
    {
        return $this->date_create;
    }

    public function setDateCreate(\DateTimeInterface $date_create): self
    {
        $this->date_create = $date_create;

        return $this;
    }

    public function getTypeId(): ?int
    {
        return $this->type_id;
    }

    public function setTypeId(int $type_id): self
    {
        $this->type_id = $type_id;

        return $this;
    }

    public function getClientId(): ?int
    {
        return $this->client_id;
    }

    public function setClientId(int $client_id): self
    {
        $this->client_id = $client_id;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getResponse(): ?string
    {
        return $this->response;
    }

    public function setResponse(?string $response): self
    {
        $this->response = $response;

        return $this;
    }

    public function getChannel(): ?string
    {
        return $this->channel;
    }

    public function setChannel(?string $channel): self
    {
        $this->channel = $channel;

        return $this;
    }

    public function getPriority(): ?int
    {
        return $this->priority;
    }

    public function setPriority(?int $priority): self
    {
        $this->priority = $priority;

        return $this;
    }

    public function getParentId(): ?int
    {
        return $this->parent_id;
    }

    public function setParentId(?int $parent_id): self
    {
        $this->parent_id = $parent_id;

        return $this;
    }
}

src/Form/RequestServiceType.php
<?php

namespace App\Form;

use App\Entity\RequestService;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RequestServiceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date_create')
            ->add('type_id')
            ->add('client_id')
            ->add('body')
            ->add('response')
            ->add('channel')
            ->add('priority')
            ->add('parent_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => RequestService::class,
        ]);
    }
}

src/Controller/RequestServiceController.php
<?php

namespace App\Controller;

use App\Entity\Client;
use App\Entity\RequestService;
use App\Entity\RequestType;
use App\Form\RequestServiceType;
use App\Repository\RequestServiceRepository;
use App\Service\PriorityServiceFacade;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/request/service")
 */
class RequestServiceController extends AbstractController
{
    /**
     * @Route("/", name="request_service_index", methods={"GET"})
     */
    public function index(RequestServiceRepository $requestServiceRepository): Response
    {
        return $this->render('request_service/index.html.twig', [
            'request_services' => $requestServiceRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="request_service_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $requestService = new RequestService();

        $clients = [];
        $clientsDoctrine = $this->getDoctrine()->getRepository(Client::class);
        $clientsAr = $clientsDoctrine->findAll();
        foreach($clientsAr as $client){
            $clients[$client->getName()] = $client->getId();
        }

        $types = [];
        $typesDoctrine = $this->getDoctrine()->getRepository(RequestType::class);
        $typesAr = $typesDoctrine->findAll();
        foreach($typesAr as $type){
            $types[$type->getName()] = $type->getId();
        }

        $form = $this->createFormBuilder($requestService)
            ->add('client_id', ChoiceType::class, array( 'choices'=>array($clients)))
            ->add('type_id', ChoiceType::class, array( 'choices'=>array($types), 'label' => 'Тип запроса'))
            ->add('body', TextareaType::class, ['label' => 'Текст запроса'])
            ->add('parent_id', NumberType::class, ['label' => 'Запрос, по которому прислано уочнение', 'required' => false])
            ->add('save', SubmitType::class, ['label' => 'отправить запрос'])->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // установка текущей даты
            $dateTime = \DateTime::createFromFormat('Y-m-d H:i:s', date('Y-m-d H:i:s'));
            $requestService->setDateCreate($dateTime);

            //Получение значения приоритета
            $priority = PriorityServiceFacade::getPriority($requestService);
            $requestService->setPriority($priority);
            echo '<pre>';
            print_r($requestService);
            echo '</pre>';


            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($requestService);
            $entityManager->flush();

            return $this->redirectToRoute('request_service_index');
        }

        return $this->render('request_service/new.html.twig', [
            'request_service' => $requestService,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="request_service_show", methods={"GET"})
     */
    public function show(RequestService $requestService): Response
    {
        return $this->render('request_service/show.html.twig', [
            'request_service' => $requestService,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="request_service_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, RequestService $requestService): Response
    {
        $form = $this->createForm(RequestServiceType::class, $requestService);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('request_service_index');
        }

        return $this->render('request_service/edit.html.twig', [
            'request_service' => $requestService,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="request_service_delete", methods={"DELETE"})
     */
    public function delete(Request $request, RequestService $requestService): Response
    {
        if ($this->isCsrfTokenValid('delete'.$requestService->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($requestService);
            $entityManager->flush();
        }

        return $this->redirectToRoute('request_service_index');
    }
}

templates/request_service/_delete_form.html.twig
<form method="post" action="{{ path('request_service_delete', {'id': request_service.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ request_service.id) }}">
    <button class="btn">Delete</button>
</form>

templates/request_service/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
{{ form_end(form) }}

templates/request_service/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit RequestService{% endblock %}

{% block body %}
    <h1>Edit RequestService</h1>

    {{ include('request_service/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('request_service_index') }}">back to list</a>

    {{ include('request_service/_delete_form.html.twig') }}
{% endblock %}

templates/request_service/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}RequestService index{% endblock %}

{% block body %}
    <h1>RequestService index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_create</th>
                <th>Type_id</th>
                <th>Client_id</th>
                <th>Body</th>
                <th>Response</th>
                <th>Channel</th>
                <th>Priority</th>
                <th>Parent_id</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for request_service in request_services %}
            <tr>
                <td>{{ request_service.id }}</td>
                <td>{{ request_service.dateCreate ? request_service.dateCreate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ request_service.typeId }}</td>
                <td>{{ request_service.clientId }}</td>
                <td>{{ request_service.body }}</td>
                <td>{{ request_service.response }}</td>
                <td>{{ request_service.channel }}</td>
                <td>{{ request_service.priority }}</td>
                <td>{{ request_service.parentId }}</td>
                <td>
                    <a href="{{ path('request_service_show', {'id': request_service.id}) }}">show</a>
                    <a href="{{ path('request_service_edit', {'id': request_service.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('request_service_new') }}">Create new</a>
{% endblock %}

templates/request_service/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Новый запрос{% endblock %}

{% block body %}
    <h1>Создание запроса</h1>

    {{ include('request_service/_form.html.twig') }}

    <a href="{{ path('request_service_index') }}">back to list</a>
{% endblock %}

templates/request_service/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}RequestService{% endblock %}

{% block body %}
    <h1>RequestService</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ request_service.id }}</td>
            </tr>
            <tr>
                <th>Date_create</th>
                <td>{{ request_service.dateCreate ? request_service.dateCreate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Type_id</th>
                <td>{{ request_service.typeId }}</td>
            </tr>
            <tr>
                <th>Client_id</th>
                <td>{{ request_service.clientId }}</td>
            </tr>
            <tr>
                <th>Body</th>
                <td>{{ request_service.body }}</td>
            </tr>
            <tr>
                <th>Response</th>
                <td>{{ request_service.response }}</td>
            </tr>
            <tr>
                <th>Channel</th>
                <td>{{ request_service.channel }}</td>
            </tr>
            <tr>
                <th>Priority</th>
                <td>{{ request_service.priority }}</td>
            </tr>
            <tr>
                <th>Parent_id</th>
                <td>{{ request_service.parentId }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('request_service_index') }}">back to list</a>

    <a href="{{ path('request_service_edit', {'id': request_service.id}) }}">edit</a>

    {{ include('request_service/_delete_form.html.twig') }}
{% endblock %}